# -*- coding: utf-8 -*-pack
{
    'name': 'Custom Shipping Cost Calculation',
    'category': 'Website',
    'author': "Vraja Technologies",
    'version': '15.0',
    'summary': """We are providing following modules, Shipping Operations, shipping, odoo shipping integration,odoo shipping connector, dhl express, fedex, ups, gls, usps, stamps.com, shipstation, bigcommerce, easyship, amazon shipping, sendclound, ebay, shopify.""",
    'description': """""",
    'depends': ['delivery'],
    'data': ['views/delivery_carrier.xml',
             'data/shipment_tracking_mail_template.xml',
             'views/res_company.xml'],
    'images': [],
    'maintainer': 'Vraja Technologies',
    'website': 'www.vrajatechnologies.com',
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'live_test_url': 'http://www.vrajatechnologies.com/contactus',
    'price': '101',
    'currency': 'EUR',
    'license': 'OPL-1',
}
